Failure # 1 (occurred at 2022-01-28_17-59-53)
Traceback (most recent call last):
  File "/home/huanting/SuperSonic/third_party/ray/tune/trial_runner.py", line 485, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/huanting/SuperSonic/third_party/ray/tune/ray_trial_executor.py", line 434, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/home/huanting/SuperSonic/third_party/ray/worker.py", line 1548, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TypeError): [36mray::SAC.train()[39m (pid=77979, ip=192.168.188.130)
  File "python/ray/_raylet.pyx", line 446, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 400, in ray._raylet.execute_task.function_executor
  File "/home/huanting/SuperSonic/third_party/ray/rllib/agents/trainer.py", line 508, in train
    raise e
  File "/home/huanting/SuperSonic/third_party/ray/rllib/agents/trainer.py", line 494, in train
    result = Trainable.train(self)
  File "/home/huanting/SuperSonic/third_party/ray/tune/trainable.py", line 268, in train
    result = self._train()
  File "/home/huanting/SuperSonic/third_party/ray/rllib/agents/trainer_template.py", line 131, in _train
    return self._train_exec_impl()
  File "/home/huanting/SuperSonic/third_party/ray/rllib/agents/trainer_template.py", line 170, in _train_exec_impl
    res = next(self.train_exec_impl)
  File "/home/huanting/SuperSonic/third_party/ray/util/iter.py", line 748, in __next__
    return next(self.built_iterator)
  File "/home/huanting/SuperSonic/third_party/ray/util/iter.py", line 762, in apply_foreach
    for item in it:
  File "/home/huanting/SuperSonic/third_party/ray/util/iter.py", line 832, in apply_filter
    for item in it:
  File "/home/huanting/SuperSonic/third_party/ray/util/iter.py", line 832, in apply_filter
    for item in it:
  File "/home/huanting/SuperSonic/third_party/ray/util/iter.py", line 762, in apply_foreach
    for item in it:
  File "/home/huanting/SuperSonic/third_party/ray/util/iter.py", line 832, in apply_filter
    for item in it:
  File "/home/huanting/SuperSonic/third_party/ray/util/iter.py", line 1073, in build_union
    item = next(it)
  File "/home/huanting/SuperSonic/third_party/ray/util/iter.py", line 748, in __next__
    return next(self.built_iterator)
  File "/home/huanting/SuperSonic/third_party/ray/util/iter.py", line 762, in apply_foreach
    for item in it:
  File "/home/huanting/SuperSonic/third_party/ray/util/iter.py", line 762, in apply_foreach
    for item in it:
  File "/home/huanting/SuperSonic/third_party/ray/util/iter.py", line 762, in apply_foreach
    for item in it:
  File "/home/huanting/SuperSonic/third_party/ray/rllib/execution/rollout_ops.py", line 81, in sampler
    yield workers.local_worker().sample()
  File "/home/huanting/SuperSonic/third_party/ray/rllib/evaluation/rollout_worker.py", line 555, in sample
    batches = [self.input_reader.next()]
  File "/home/huanting/SuperSonic/third_party/ray/rllib/evaluation/sampler.py", line 57, in next
    batches = [self.get_data()]
  File "/home/huanting/SuperSonic/third_party/ray/rllib/evaluation/sampler.py", line 178, in get_data
    item = next(self.rollout_provider)
  File "/home/huanting/SuperSonic/third_party/ray/rllib/evaluation/sampler.py", line 572, in _env_runner
    base_env.send_actions(actions_to_send)
  File "/home/huanting/SuperSonic/third_party/ray/rllib/env/base_env.py", line 329, in send_actions
    self.vector_env.vector_step(action_vector)
  File "/home/huanting/SuperSonic/third_party/ray/rllib/env/vector_env.py", line 136, in vector_step
    obs, r, done, info = self.envs[i].step(actions[i])
  File "/home/huanting/SuperSonic/SuperSonic/utils/environments/stoke_rl_env.py", line 88, in step
    obs, rew, done, info = self.env.step(action, state_code, state_reward)
  File "/home/huanting/SuperSonic/third_party/compiler_gym/envs/optimization/Stoke.py", line 139, in step
    rew = self.get_reward(reward,self.reward_function)  # update reward
  File "/home/huanting/SuperSonic/third_party/compiler_gym/envs/optimization/Stoke.py", line 101, in get_reward
    reward = reward_function().get_reward(reward,reward_function=reward_function
TypeError: 'float' object is not callable

